import { NavLink, Outlet, useNavigate } from 'react-router-dom';
import { Bell, BookOpen, Calendar, CheckSquare, Home, Menu, Search, Settings, User, ArrowLeft } from 'lucide-react';
import { motion } from 'framer-motion';

const nav = [{to:'/dashboard',label:'Dashboard',icon:Home},{to:'/calendar',label:'Calendário',icon:Calendar},{to:'/tasks',label:'Tarefas',icon:CheckSquare},{to:'/notes',label:'Notas',icon:BookOpen},{to:'/profile',label:'Perfil',icon:User}];

export function Header({ title, back=false, search=false, avatar=true, notifications=true, menu=true }: {title:string;back?:boolean;search?:boolean;avatar?:boolean;notifications?:boolean;menu?:boolean}){ const navigate=useNavigate(); return <header className="sticky top-0 z-30 border-b border-[#eae3d2]/80 bg-[#fdfbf7]/85 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl items-center gap-3 px-4 py-3"><button aria-label="Voltar" onClick={()=>navigate(-1)} className={`focus-ring rounded-full p-2 ${back?'':'invisible'}`}><ArrowLeft size={20}/></button><h1 className="flex-1 font-serif text-2xl text-[#1a1918]">{title}</h1>{search&&<button aria-label="Pesquisar" className="focus-ring rounded-full p-2"><Search size={20}/></button>}{notifications&&<button aria-label="Notificações" className="focus-ring rounded-full p-2"><Bell size={20}/></button>}{avatar&&<button aria-label="Perfil" className="focus-ring rounded-full p-2"><User size={20}/></button>}{menu&&<button aria-label="Menu" className="focus-ring rounded-full p-2 md:hidden"><Menu size={20}/></button>}</div></header> }

function SideNavigation(){ return <aside className="sticky top-0 hidden h-screen w-72 shrink-0 border-r border-[#eae3d2] bg-white/55 p-5 md:block"><div className="mb-8 flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-full border border-[#c5a077] font-serif italic text-[#9c784e]">SG</div><span className="text-xs uppercase tracking-[.24em] text-[#7c7267]">SG-Org</span></div><nav aria-label="Navegação lateral" className="space-y-2">{nav.map(({to,label,icon:Icon})=><NavLink key={to} to={to} className={({isActive})=>`focus-ring flex items-center gap-3 rounded-2xl px-4 py-3 text-sm transition ${isActive?'bg-[#f3eadc] text-[#2c2a29]':'text-[#7c7267] hover:bg-[#f7f4eb]'}`}><Icon size={18}/>{label}</NavLink>)}<NavLink to="/settings" className="focus-ring flex items-center gap-3 rounded-2xl px-4 py-3 text-sm text-[#7c7267] hover:bg-[#f7f4eb]"><Settings size={18}/>Definições</NavLink></nav></aside> }
function BottomNavigation(){ return <nav aria-label="Navegação inferior" className="safe-bottom fixed inset-x-0 bottom-0 z-40 border-t border-[#eae3d2] bg-[#fdfbf7]/90 px-2 pt-2 backdrop-blur-xl md:hidden"> <div className="mx-auto grid max-w-md grid-cols-5">{nav.map(({to,label,icon:Icon})=><NavLink key={to} to={to} className={({isActive})=>`focus-ring rounded-2xl px-2 py-2 text-center text-[11px] transition ${isActive?'text-[#9c784e]':'text-[#7c7267]'}`}><Icon className="mx-auto mb-1" size={20}/>{label}</NavLink>)}</div></nav> }
export function FloatingActions(){return <button aria-label="Ação rápida" className="focus-ring fixed bottom-24 right-5 z-40 rounded-full bg-[#9c784e] px-5 py-4 text-white shadow-xl md:bottom-6">+</button>}
export function AppShell(){ return <div className="app-bg min-h-screen text-[#2c2a29]"><div className="flex"><SideNavigation/><div className="min-w-0 flex-1"><Header title="SG-Org" search/><motion.main initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{duration:.35}} className="mx-auto max-w-6xl px-4 pb-32 pt-5 md:pb-10"><Outlet/></motion.main><FloatingActions/><BottomNavigation/><div id="dialogs"/><div id="toasts" aria-live="polite"/></div></div></div> }
