import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { EmptyState } from '../components/states/States';
import { ContentLoading } from '../components/loading/Loading';

const pageNames: Record<string,string>={dashboard:'Dashboard',calendar:'Calendário',tasks:'Tarefas',notes:'Notas',profile:'Perfil',settings:'Definições'};
export function Login(){return <main className="app-bg grid min-h-screen place-items-center p-6"><section className="card max-w-md rounded-[2rem] p-8 text-center"><div className="mx-auto mb-4 grid h-20 w-20 place-items-center rounded-full border border-[#c5a077] font-serif text-3xl italic text-[#9c784e]">SG</div><h1 className="font-serif text-3xl">Autenticação</h1><p className="mt-3 text-sm text-[#7c7267]">Estrutura preparada para Login, Registo e Recuperação de Password na Parte 1C.</p><Link className="focus-ring mt-6 inline-block rounded-full bg-[#9c784e] px-5 py-3 text-white" to="/home">Pré-visualizar Home</Link></section></main>}
export function Home(){return <div className="space-y-5"><section className="card rounded-[2rem] p-6"><p className="text-xs uppercase tracking-[.24em] text-[#a39788]">Hoje</p><h2 className="mt-2 font-serif text-3xl">A sua história, organizada ao detalhe.</h2><p className="mt-3 text-[#7c7267]">Resumo, próximos eventos, tarefas, notas recentes e atalhos rápidos.</p></section><div className="grid gap-4 md:grid-cols-2"><Placeholder title="Resumo"/><EmptyState kind="events"/><EmptyState kind="tasks"/><EmptyState kind="notes"/></div><section className="grid gap-3 sm:grid-cols-3"><Link to="/calendar" className="card focus-ring rounded-3xl p-5">Calendário</Link><Link to="/tasks" className="card focus-ring rounded-3xl p-5">Tarefas</Link><Link to="/notes" className="card focus-ring rounded-3xl p-5">Notas</Link></section></div>}
function Placeholder({title}:{title:string}){return <section className="card rounded-3xl p-5"><h2 className="mb-4 font-serif text-xl">{title}</h2><ContentLoading/></section>}
export function AppPage({kind}:{kind:keyof typeof pageNames}){return <motion.div initial={{opacity:0}} animate={{opacity:1}} className="space-y-4"><h2 className="font-serif text-3xl">{pageNames[kind]}</h2><Placeholder title={`Estrutura de ${pageNames[kind]}`}/></motion.div>}
export function NotFound(){return <main className="app-bg grid min-h-screen place-items-center p-6"><EmptyState kind="notFound"/></main>}
